[package]
name = "advent_of_code"
version = "0.1.0"
authors = ["Robbe Van Herck <robbe@robbevanherck.be>"]
edition = "2018"

[dependencies]
itertools = "0.9.0"
structopt = "0.3.13"
rand = "0.7.1"
regex = "1.4.2"
lazy_static = "1.4.0"
